require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassifiedAdsController do

  # This should return the minimal set of attributes required to create a valid
  # ClassifiedAd. As you add validations to ClassifiedAd, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :item_id => Item.last || Item.create!(:name => 'TEST') }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClassifiedAdsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all classified_ads as @classified_ads" do
      classified_ad = ClassifiedAd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:classified_ads).should eq([classified_ad])
    end
  end

  describe "GET show" do
    it "assigns the requested classified_ad as @classified_ad" do
      classified_ad = ClassifiedAd.create! valid_attributes
      get :show, {:id => classified_ad.to_param}, valid_session
      assigns(:classified_ad).should eq(classified_ad)
    end
  end

  describe "GET new" do
    it "assigns a new classified_ad as @classified_ad" do
      get :new, {}, valid_session
      assigns(:classified_ad).should be_a_new(ClassifiedAd)
    end
  end

  describe "GET edit" do
    it "assigns the requested classified_ad as @classified_ad" do
      classified_ad = ClassifiedAd.create! valid_attributes
      get :edit, {:id => classified_ad.to_param}, valid_session
      assigns(:classified_ad).should eq(classified_ad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClassifiedAd" do
        expect {
          post :create, {:classified_ad => valid_attributes}, valid_session
        }.to change(ClassifiedAd, :count).by(1)
      end

      it "assigns a newly created classified_ad as @classified_ad" do
        post :create, {:classified_ad => valid_attributes}, valid_session
        assigns(:classified_ad).should be_a(ClassifiedAd)
        assigns(:classified_ad).should be_persisted
      end

      it "redirects to the classified_ads" do
        post :create, {:classified_ad => valid_attributes}, valid_session
        response.should redirect_to(classified_ads_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved classified_ad as @classified_ad" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassifiedAd.any_instance.stub(:save).and_return(false)
        post :create, {:classified_ad => {}}, valid_session
        assigns(:classified_ad).should be_a_new(ClassifiedAd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassifiedAd.any_instance.stub(:save).and_return(false)
        post :create, {:classified_ad => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested classified_ad" do
        classified_ad = ClassifiedAd.create! valid_attributes
        # Assuming there are no other classified_ads in the database, this
        # specifies that the ClassifiedAd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClassifiedAd.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => classified_ad.to_param, :classified_ad => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested classified_ad as @classified_ad" do
        classified_ad = ClassifiedAd.create! valid_attributes
        put :update, {:id => classified_ad.to_param, :classified_ad => valid_attributes}, valid_session
        assigns(:classified_ad).should eq(classified_ad)
      end

      it "redirects to the classified_ad" do
        classified_ad = ClassifiedAd.create! valid_attributes
        put :update, {:id => classified_ad.to_param, :classified_ad => valid_attributes}, valid_session
        response.should redirect_to(classified_ad)
      end
    end

    describe "with invalid params" do
      it "assigns the classified_ad as @classified_ad" do
        classified_ad = ClassifiedAd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassifiedAd.any_instance.stub(:save).and_return(false)
        put :update, {:id => classified_ad.to_param, :classified_ad => {}}, valid_session
        assigns(:classified_ad).should eq(classified_ad)
      end

      it "re-renders the 'edit' template" do
        classified_ad = ClassifiedAd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassifiedAd.any_instance.stub(:save).and_return(false)
        put :update, {:id => classified_ad.to_param, :classified_ad => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested classified_ad" do
      classified_ad = ClassifiedAd.create! valid_attributes
      expect {
        delete :destroy, {:id => classified_ad.to_param}, valid_session
      }.to change(ClassifiedAd, :count).by(-1)
    end

    it "redirects to the classified_ads list" do
      classified_ad = ClassifiedAd.create! valid_attributes
      delete :destroy, {:id => classified_ad.to_param}, valid_session
      response.should redirect_to(classified_ads_url)
    end
  end

end
